### ISSUE TITLE
add screenshot

### ISSUE THREAD

**Issue by GochoMugo** [zaccolley/shh#1]
Just installed it! Its the most fun command I have used recently. Kudos!

Do you mind adding a screenshot? It would help make people see what awesomeness it does. I suggest http://asciinema.org/. Check it out.

**Comment by zoetrope69** [comment]
im gonna leave it a mystery as to what it shows but will add more to the readme haha

**Comment by GochoMugo** [comment]
Wow! I like the mystery thing! Add some meat to the readme to invoke more curiosity. **shh**!!!!

**Comment by zoetrope69** [comment]
ok added more mystery :wink: 
https://github.com/zaccolley/shh/commit/d6f88a9dc499344633f523139e6918a0f08f74d9
